const fs = require('fs');
const path = require('path');

const run = () => {



    fs.readFile(path.join(__dirname, 'metros.json'), (err, data) => {
        if (err) throw err;

       let arr = ["Alameda",
"Albany",
"Berkeley",
"Dublin",
"Emeryville",
"Fremont",
"Hayward",
"Livermore",
"Newark",
"Oakland",
"Piedmont",
"Pleasanton",
"San Leandro",
"Union City",
"Unincorporated Alameda",
"Antioch",
"Brentwood",
"Clayton",
"Concord",
"Danville",
"El Cerrito",
"Hercules",
"Lafayette",
"Martinez",
"Moraga",
"Orinda",
"Pinole",
"Pittsburg",
"Pleasant Hill",
"Richmond",
"San Pablo",
"San Ramon",
"Walnut Creek",
"Unincorporated Contra Costa",
"Belvedere",
"Corte Madera",
"Fairfax",
"Larkspur",
"Mill Valley",
"Novato",
"Ross",
"San Anselmo",
"San Rafael",
"Sausalito",
"Tiburon",
"Unincorporated Marin",
"Calistoga",
"Napa",
"St. Helena",
"Yountville",
"Unincorporated Napa",
"San Francisco",
"Atherton",
"Belmont",
"Brisbane",
"Burlingame",
"Colma",
"Daly City",
"East Palo Alto",
"Foster City",
"Half Moon Bay",
"Hillsborough",
"Menlo Park",
"Millbrae",
"Pacifica",
"Portola Valley",
"Redwood City",
"San Bruno",
"San Carlos",
"San Mateo",
"South San Francisco",
"Woodside",
"Unincorporated San Mateo",
"Campbell",
"Cupertino",
"Gilroy",
"Los Altos",
"Los Altos Hills",
"Los Gatos",
"Milpitas",
"Monte Sereno",
"Morgan Hill",
"Mountain View",
"Palo Alto",
"San Jose",
"Santa Clara",
"Saratoga",
"Sunnyvale",
"Unincorporated Santa Clara",
"Benicia",
"Dixon",
"Fairfield",
"Rio Vista",
"Suisun City",
"Vacaville",
"Vallejo",
"Unincorporated Solano",
"Cloverdale",
"Cotati",
"Healdsburg",
"Petaluma",
"Rohnert Park",
"Santa Rosa",
"Sebastopol",
"Sonoma",
"Unincorporated Sonoma",
"Alameda",
"Albany",
"Berkeley",
"Dublin",
"Emeryville",
"Fremont",
"Hayward",
"Livermore",
"Newark",
"Oakland",
"Piedmont",
"Pleasanton",
"San Leandro",
"Union City",
"Unincorporated Alameda",
"Antioch",
"Brentwood",
"Clayton",
"Concord",
"Danville",
"El Cerrito",
"Hercules",
"Lafayette",
"Martinez",
"Moraga",
"Orinda",
"Pinole",
"Pittsburg",
"Pleasant Hill",
"Richmond",
"San Pablo",
"San Ramon",
"Walnut Creek",
"Unincorporated Contra Costa",
"Belvedere",
"Corte Madera",
"Fairfax",
"Larkspur",
"Mill Valley",
"Novato",
"Ross",
"San Anselmo",
"San Rafael",
"Sausalito",
"Tiburon",
"Unincorporated Marin",
"American Canyon",
"Calistoga",
"Napa",
"St. Helena",
"Yountville",
"Unincorporated Napa",
"San Francisco",
"Atherton",
"Belmont",
"Brisbane",
"Burlingame",
"Colma",
"Daly City",
"East Palo Alto",
"Foster City",
"Half Moon Bay",
"Hillsborough",
"Menlo Park",
"Millbrae",
"Pacifica",
"Portola Valley",
"Redwood City",
"San Bruno",
"San Carlos",
"San Mateo",
"South San Francisco",
"Woodside",
"Unincorporated San Mateo",
"Campbell",
"Cupertino",
"Gilroy",
"Los Altos",
"Los Altos Hills",
"Los Gatos",
"Milpitas",
"Monte Sereno",
"Morgan Hill",
"Mountain View",
"Palo Alto",
"San Jose",
"Santa Clara",
"Saratoga",
"Sunnyvale",
"Unincorporated Santa Clara",
"Benicia",
"Dixon",
"Fairfield",
"Rio Vista",
"Suisun City",
"Vacaville",
"Vallejo",
"Unincorporated Solano",
"Cloverdale",
"Cotati",
"Healdsburg",
"Petaluma",
"Rohnert Park",
"Santa Rosa",
"Sebastopol",
"Sonoma",
"Unincorporated Sonoma",
"Alameda",
"Albany",
"Berkeley",
"Dublin",
"Emeryville",
"Fremont",
"Hayward",
"Livermore",
"Newark",
"Oakland",
"Piedmont",
"Pleasanton",
"San Leandro",
"Union City",
"Unincorporated Alameda",
"Antioch",
"Brentwood",
"Clayton",
"Concord",
"Danville",
"El Cerrito",
"Hercules",
"Lafayette",
"Martinez",
"Moraga",
"Orinda",
"Pinole",
"Pittsburg",
"Pleasant Hill",
"Richmond",
"San Pablo",
"San Ramon",
"Walnut Creek",
"Unincorporated Contra Costa",
"Belvedere",
"Corte Madera",
"Fairfax",
"Larkspur",
"Mill Valley",
"Novato",
"Ross",
"San Anselmo",
"San Rafael",
"Sausalito",
"Tiburon",
"Unincorporated Marin",
"American Canyon",
"Calistoga",
"Napa",
"St. Helena",
"Yountville",
"Unincorporated Napa",
"San Francisco",
"Atherton",
"Belmont",
"Brisbane",
"Burlingame",
"Colma",
"Daly City",
"East Palo Alto",
"Foster City",
"Half Moon Bay",
"Hillsborough",
"Menlo Park",
"Millbrae",
"Pacifica",
"Portola Valley",
"Redwood City",
"San Bruno",
"San Carlos",
"San Mateo",
"South San Francisco",
"Woodside",
"Unincorporated San Mateo",
"Campbell",
"Cupertino",
"Gilroy",
"Los Altos",
"Los Altos Hills",
"Los Gatos",
"Milpitas",
"Monte Sereno",
"Morgan Hill",
"Mountain View",
"Palo Alto",
"San Jose",
"Santa Clara",
"Saratoga",
"Sunnyvale",
"Unincorporated Santa Clara",
"Benicia",
"Dixon",
"Fairfield",
"Rio Vista",
"Suisun City",
"Vacaville",
"Vallejo",
"Unincorporated Solano",
"Cloverdale",
"Cotati",
"Healdsburg",
"Petaluma",
"Rohnert Park",
"Santa Rosa",
"Sebastopol",
"Sonoma",
"Windsor",
"Unincorporated Sonoma",
"Alameda",
"Albany",
"Berkeley",
"Dublin",
"Emeryville",
"Fremont",
"Hayward",
"Livermore",
"Newark",
"Oakland",
"Piedmont",
"Pleasanton",
"San Leandro",
"Union City",
"Unincorporated Alameda",
"Antioch",
"Brentwood",
"Clayton",
"Concord",
"Danville",
"El Cerrito",
"Hercules",
"Lafayette",
"Martinez",
"Moraga",
"Orinda",
"Pinole",
"Pittsburg",
"Pleasant Hill",
"Richmond",
"San Pablo",
"San Ramon",
"Walnut Creek",
"Unincorporated Contra Costa",
"Belvedere",
"Corte Madera",
"Fairfax",
"Larkspur",
"Mill Valley",
"Novato",
"Ross",
"San Anselmo",
"San Rafael",
"Sausalito",
"Tiburon",
"Unincorporated Marin",
"American Canyon",
"Calistoga",
"Napa",
"St. Helena",
"Yountville",
"Unincorporated Napa",
"San Francisco",
"Atherton",
"Belmont",
"Brisbane",
"Burlingame",
"Colma",
"Daly City",
"East Palo Alto",
"Foster City",
"Half Moon Bay",
"Hillsborough",
"Menlo Park",
"Millbrae",
"Pacifica",
"Portola Valley",
"Redwood City",
"San Bruno",
"San Carlos",
"San Mateo",
"South San Francisco",
"Woodside",
"Unincorporated San Mateo",
"Campbell",
"Cupertino",
"Gilroy",
"Los Altos",
"Los Altos Hills",
"Los Gatos",
"Milpitas",
"Monte Sereno",
"Morgan Hill",
"Mountain View",
"Palo Alto",
"San Jose",
"Santa Clara",
"Saratoga",
"Sunnyvale",
"Unincorporated Santa Clara",
"Benicia",
"Dixon",
"Fairfield",
"Rio Vista",
"Suisun City",
"Vacaville",
"Vallejo",
"Unincorporated Solano",
"Cloverdale",
"Cotati",
"Healdsburg",
"Petaluma",
"Rohnert Park",
"Santa Rosa",
"Sebastopol",
"Sonoma",
"Windsor",
"Unincorporated Sonoma",
"Alameda",
"Albany",
"Berkeley",
"Dublin",
"Emeryville",
"Fremont",
"Hayward",
"Livermore",
"Newark",
"Oakland",
"Piedmont",
"Pleasanton",
"San Leandro",
"Union City",
"Unincorporated Alameda",
"Antioch",
"Brentwood",
"Clayton",
"Concord",
"Danville",
"El Cerrito",
"Hercules",
"Lafayette",
"Martinez",
"Moraga",
"Orinda",
"Pinole",
"Pittsburg",
"Pleasant Hill",
"Richmond",
"San Pablo",
"San Ramon",
"Walnut Creek",
"Unincorporated Contra Costa",
"Belvedere",
"Corte Madera",
"Fairfax",
"Larkspur",
"Mill Valley",
"Novato",
"Ross",
"San Anselmo",
"San Rafael",
"Sausalito",
"Tiburon",
"Unincorporated Marin",
"American Canyon",
"Calistoga",
"Napa",
"St. Helena",
"Yountville",
"Unincorporated Napa",
"San Francisco",
"Atherton",
"Belmont",
"Brisbane",
"Burlingame",
"Colma",
"Daly City",
"East Palo Alto",
"Foster City",
"Half Moon Bay",
"Hillsborough",
"Menlo Park",
"Millbrae",
"Pacifica",
"Portola Valley",
"Redwood City",
"San Bruno",
"San Carlos",
"San Mateo",
"South San Francisco",
"Woodside",
"Unincorporated San Mateo",
"Campbell",
"Cupertino",
"Gilroy",
"Los Altos",
"Los Altos Hills",
"Los Gatos",
"Milpitas",
"Monte Sereno",
"Morgan Hill",
"Mountain View",
"Palo Alto",
"San Jose",
"Santa Clara",
"Saratoga",
"Sunnyvale",
"Unincorporated Santa Clara",
"Benicia",
"Dixon",
"Fairfield",
"Rio Vista",
"Suisun City",
"Vacaville",
"Vallejo",
"Unincorporated Solano",
"Cloverdale",
"Cotati",
"Healdsburg",
"Petaluma",
"Rohnert Park",
"Santa Rosa",
"Sebastopol",
"Sonoma",
"Windsor",
"Unincorporated Sonoma",
"Alameda",
"Albany",
"Berkeley",
"Dublin",
"Emeryville",
"Fremont",
"Hayward",
"Livermore",
"Newark",
"Oakland",
"Piedmont",
"Pleasanton",
"San Leandro",
"Union City",
"Unincorporated Alameda",
"Antioch",
"Brentwood",
"Clayton",
"Concord",
"Danville",
"El Cerrito",
"Hercules",
"Lafayette",
"Martinez",
"Moraga",
"Orinda",
"Pinole",
"Pittsburg",
"Pleasant Hill",
"Richmond",
"San Pablo",
"San Ramon",
"Walnut Creek",
"Unincorporated Contra Costa",
"Belvedere",
"Corte Madera",
"Fairfax",
"Larkspur",
"Mill Valley",
"Novato",
"Ross",
"San Anselmo",
"San Rafael",
"Sausalito",
"Tiburon",
"Unincorporated Marin",
"American Canyon",
"Calistoga",
"Napa",
"St. Helena",
"Yountville",
"Unincorporated Napa",
"San Francisco",
"Atherton",
"Belmont",
"Brisbane",
"Burlingame",
"Colma",
"Daly City",
"East Palo Alto",
"Foster City",
"Half Moon Bay",
"Hillsborough",
"Menlo Park",
"Millbrae",
"Pacifica",
"Portola Valley",
"Redwood City",
"San Bruno",
"San Carlos",
"San Mateo",
"South San Francisco",
"Woodside",
"Unincorporated San Mateo",
"Campbell",
"Cupertino",
"Gilroy",
"Los Altos",
"Los Altos Hills",
"Los Gatos",
"Milpitas",
"Monte Sereno",
"Morgan Hill",
"Mountain View",
"Palo Alto",
"San Jose",
"Santa Clara",
"Saratoga",
"Sunnyvale",
"Unincorporated Santa Clara",
"Benicia",
"Dixon",
"Fairfield",
"Rio Vista",
"Suisun City",
"Vacaville",
"Vallejo",
"Unincorporated Solano",
"Cloverdale",
"Cotati",
"Healdsburg",
"Petaluma",
"Rohnert Park",
"Santa Rosa",
"Sebastopol",
"Sonoma",
"Windsor",
"Unincorporated Sonoma",
"Alameda",
"Albany",
"Berkeley",
"Dublin",
"Emeryville",
"Fremont",
"Hayward",
"Livermore",
"Newark",
"Oakland",
"Piedmont",
"Pleasanton",
"San Leandro",
"Union City",
"Unincorporated Alameda",
"Antioch",
"Brentwood",
"Clayton",
"Concord",
"Danville",
"El Cerrito",
"Hercules",
"Lafayette",
"Martinez",
"Moraga",
"Orinda",
"Pinole",
"Pittsburg",
"Pleasant Hill",
"Richmond",
"San Pablo",
"San Ramon",
"Walnut Creek",
"Unincorporated Contra Costa",
"Belvedere",
"Corte Madera",
"Fairfax",
"Larkspur",
"Mill Valley",
"Novato",
"Ross",
"San Anselmo",
"San Rafael",
"Sausalito",
"Tiburon",
"Unincorporated Marin",
"American Canyon",
"Calistoga",
"Napa",
"St. Helena",
"Yountville",
"Unincorporated Napa",
"San Francisco",
"Atherton",
"Belmont",
"Brisbane",
"Burlingame",
"Colma",
"Daly City",
"East Palo Alto",
"Foster City",
"Half Moon Bay",
"Hillsborough",
"Menlo Park",
"Millbrae",
"Pacifica",
"Portola Valley",
"Redwood City",
"San Bruno",
"San Carlos",
"San Mateo",
"South San Francisco",
"Woodside",
"Unincorporated San Mateo",
"Campbell",
"Cupertino",
"Gilroy",
"Los Altos",
"Los Altos Hills",
"Los Gatos",
"Milpitas",
"Monte Sereno",
"Morgan Hill",
"Mountain View",
"Palo Alto",
"San Jose",
"Santa Clara",
"Saratoga",
"Sunnyvale",
"Unincorporated Santa Clara",
"Benicia",
"Dixon",
"Fairfield",
"Rio Vista",
"Suisun City",
"Vacaville",
"Vallejo",
"Unincorporated Solano",
"Cloverdale",
"Cotati",
"Healdsburg",
"Petaluma",
"Rohnert Park",
"Santa Rosa",
"Sebastopol",
"Sonoma",
"Windsor",
"Unincorporated Sonoma",
"Alameda",
"Albany",
"Berkeley",
"Dublin",
"Emeryville",
"Fremont",
"Hayward",
"Livermore",
"Newark",
"Oakland",
"Piedmont",
"Pleasanton",
"San Leandro",
"Union City",
"Unincorporated Alameda",
"Antioch",
"Brentwood",
"Clayton",
"Concord",
"Danville",
"El Cerrito",
"Hercules",
"Lafayette",
"Martinez",
"Moraga",
"Orinda",
"Pinole",
"Pittsburg",
"Pleasant Hill",
"Richmond",
"San Pablo",
"San Ramon",
"Walnut Creek",
"Unincorporated Contra Costa",
"Belvedere",
"Corte Madera",
"Fairfax",
"Larkspur",
"Mill Valley",
"Novato",
"Ross",
"San Anselmo",
"San Rafael",
"Sausalito",
"Tiburon",
"Unincorporated Marin",
"American Canyon",
"Calistoga",
"Napa",
"St. Helena",
"Yountville",
"Unincorporated Napa",
"San Francisco",
"Atherton",
"Belmont",
"Brisbane",
"Burlingame",
"Colma",
"Daly City",
"East Palo Alto",
"Foster City",
"Half Moon Bay",
"Hillsborough",
"Menlo Park",
"Millbrae",
"Pacifica",
"Portola Valley",
"Redwood City",
"San Bruno",
"San Carlos",
"San Mateo",
"South San Francisco",
"Woodside",
"Unincorporated San Mateo",
"Campbell",
"Cupertino",
"Gilroy",
"Los Altos",
"Los Altos Hills",
"Los Gatos",
"Milpitas",
"Monte Sereno",
"Morgan Hill",
"Mountain View",
"Palo Alto",
"San Jose",
"Santa Clara",
"Saratoga",
"Sunnyvale",
"Unincorporated Santa Clara",
"Benicia",
"Dixon",
"Fairfield",
"Rio Vista",
"Suisun City",
"Vacaville",
"Vallejo",
"Unincorporated Solano",
"Cloverdale",
"Cotati",
"Healdsburg",
"Petaluma",
"Rohnert Park",
"Santa Rosa",
"Sebastopol",
"Sonoma",
"Windsor",
"Unincorporated Sonoma",
"Alameda",
"Albany",
"Berkeley",
"Dublin",
"Emeryville",
"Fremont",
"Hayward",
"Livermore",
"Newark",
"Oakland",
"Piedmont",
"Pleasanton",
"San Leandro",
"Union City",
"Unincorporated Alameda",
"Antioch",
"Brentwood",
"Clayton",
"Concord",
"Danville",
"El Cerrito",
"Hercules",
"Lafayette",
"Martinez",
"Moraga",
"Orinda",
"Pinole",
"Pittsburg",
"Pleasant Hill",
"Richmond",
"San Pablo",
"San Ramon",
"Walnut Creek",
"Unincorporated Contra Costa",
"Belvedere",
"Corte Madera",
"Fairfax",
"Larkspur",
"Mill Valley",
"Novato",
"Ross",
"San Anselmo",
"San Rafael",
"Sausalito",
"Tiburon",
"Unincorporated Marin",
"American Canyon",
"Calistoga",
"Napa",
"St. Helena",
"Yountville",
"Unincorporated Napa",
"San Francisco",
"Atherton",
"Belmont",
"Brisbane",
"Burlingame",
"Colma",
"Daly City",
"East Palo Alto",
"Foster City",
"Half Moon Bay",
"Hillsborough",
"Menlo Park",
"Millbrae",
"Pacifica",
"Portola Valley",
"Redwood City",
"San Bruno",
"San Carlos",
"San Mateo",
"South San Francisco",
"Woodside",
"Unincorporated San Mateo",
"Campbell",
"Cupertino",
"Gilroy",
"Los Altos",
"Los Altos Hills",
"Los Gatos",
"Milpitas",
"Monte Sereno",
"Morgan Hill",
"Mountain View",
"Palo Alto",
"San Jose",
"Santa Clara",
"Saratoga",
"Sunnyvale",
"Unincorporated Santa Clara",
"Benicia",
"Dixon",
"Fairfield",
"Rio Vista",
"Suisun City",
"Vacaville",
"Vallejo",
"Unincorporated Solano",
"Cloverdale",
"Cotati",
"Healdsburg",
"Petaluma",
"Rohnert Park",
"Santa Rosa",
"Sebastopol",
"Sonoma",
"Windsor",
"Unincorporated Sonoma",
"Alameda",
"Albany",
"Berkeley",
"Dublin",
"Emeryville",
"Fremont",
"Hayward",
"Livermore",
"Newark",
"Oakland",
"Piedmont",
"Pleasanton",
"San Leandro",
"Union City",
"Unincorporated Alameda",
"Antioch",
"Brentwood",
"Clayton",
"Concord",
"Danville",
"El Cerrito",
"Hercules",
"Lafayette",
"Martinez",
"Moraga",
"Oakley",
"Orinda",
"Pinole",
"Pittsburg",
"Pleasant Hill",
"Richmond" ]

const uniqueArr = [...new Set(arr)];
console.log(JSON.stringify(uniqueArr)); // [1, 2, 3, 4, 5]


        // console.log(data)
        // const jsonData = JSON.parse(data);

        // let uniqueCities = []
        

        
        // for (let record of jsonData) {
        //     console.log(record.city)
            
        //     // if (!Object.keys(uniqueCities).includes()) {
        //     //     let newRecord = { city: record.city,  lat: '', long: ''  }
        //     //     uniqueCities.push(newRecord)
        //     // }
        // }
        // console.log(uniqueCities)

        // fs.writeFile('cities.json', JSON.stringify(uniqueCities), (err) => {
        //     if (err) throw err;
        //     console.log('Data written to file');
        // });

        
        
    });
}
run();